# Generated by Django 3.2 on 2023-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contactusform'),
        ('products', '0009_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='product_likes', to='profiles.UserProfile'),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
